In [78]:
import numpy as np

In [79]:
np_liste = np.array(list(range(1,11)))
np_2d = np_liste.reshape(5,2)
np_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [80]:
np_2d[0]

array([1, 2])

In [81]:
np_5 = np.arange(5,25,5)
np_5

array([ 5, 10, 15, 20])

In [82]:
np1 = np.ones((10,10))
np1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [83]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [84]:
eyes = np.eye(3,3)
eyes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
liste = np.random.randint(1,101,(10000))
print(liste)

[15 89 76 ... 68 96 86]


In [86]:
np.count_nonzero(liste == 1)

107

In [87]:
names_list = ["Alihan Ayverdi",
"Ahmet KOÇ",
"ÖMER FARUK KÖSE",
"Merve DEMİR",
"Rıza Efe Dönmez ",
"Nergis KAHVECİOĞLU",
"EMİNE ÇETİN",
"Safiye Esmanur AYDAR",
"Yasmın Zhulfayeva",
"Ali Burkay KÜÇÜKAKCA",
"Sıla SARAÇ",
"Melike Nur ÇOTAK",
"Sabahattin MAKİNE",
"Gülsüm",
"Muhammed Mustafa SAVAR"]


np.random.choice(names_list, replace=False, size=5)

array(['Ahmet KOÇ', 'Sabahattin MAKİNE', 'Gülsüm', 'Melike Nur ÇOTAK',
       'Merve DEMİR'], dtype='<U22')

In [88]:
np.flipud(liste) # ters cevirme

array([86, 96, 68, ..., 76, 89, 15])

In [89]:
np.max(liste) #maximum

np.int64(100)

In [90]:
np.min(liste) #minumum

np.int64(1)

In [91]:
np.mean(liste) #ortalama

np.float64(50.4216)

In [92]:
np.std(liste) #standart sapma

np.float64(28.769234495203378)

In [93]:
len(liste) #eleman sayısı

10000

In [94]:
notlar = np.random.randint(50, 101, 20)
notlar

array([83, 83, 71, 73, 96, 56, 81, 91, 96, 93, 88, 93, 80, 57, 92, 94, 93,
       63, 99, 68])

In [95]:
np.savetxt("notlar.txt", notlar) #bilimsel gösterim

In [96]:
#bilimsel olmayan gösterim
np.savetxt("notlar.txt", notlar, fmt="%d")

In [97]:
ls

datatypes.jpeg      ders2.ipynb         kısayollar.jpeg     numpy_array_t.jpeg
ders1.ipynb         exercise.ipynb      notlar.txt


In [98]:
notlar = np.loadtxt("notlar.txt")

In [99]:
notlar

array([83., 83., 71., 73., 96., 56., 81., 91., 96., 93., 88., 93., 80.,
       57., 92., 94., 93., 63., 99., 68.])

In [100]:
np.sort(notlar)

array([56., 57., 63., 68., 71., 73., 80., 81., 83., 83., 88., 91., 92.,
       93., 93., 93., 94., 96., 96., 99.])

In [101]:
#reverse sort
np.sort(notlar)[::-1]

array([99., 96., 96., 94., 93., 93., 93., 92., 91., 88., 83., 83., 81.,
       80., 73., 71., 68., 63., 57., 56.])