In [163]:
import numpy as np

In [164]:
np_liste = np.array(list(range(1,11)))
np_2d = np_liste.reshape(5,2)
np_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [165]:
np_2d[0]

array([1, 2])

In [166]:
np_5 = np.arange(5,25,5)
np_5

array([ 5, 10, 15, 20])

In [167]:
np1 = np.ones((10,10))
np1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [168]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [169]:
eyes = np.eye(3,3)
eyes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [170]:
liste = np.random.randint(1,101,(10000))
print(liste)

[ 9 40 28 ... 20 94 78]


In [171]:
np.count_nonzero(liste == 1)

90

In [172]:
names_list = ["Alihan Ayverdi",
"Ahmet KOÇ",
"ÖMER FARUK KÖSE",
"Merve DEMİR",
"Rıza Efe Dönmez ",
"Nergis KAHVECİOĞLU",
"EMİNE ÇETİN",
"Safiye Esmanur AYDAR",
"Yasmın Zhulfayeva",
"Ali Burkay KÜÇÜKAKCA",
"Sıla SARAÇ",
"Melike Nur ÇOTAK",
"Sabahattin MAKİNE",
"Gülsüm",
"Muhammed Mustafa SAVAR"]


np.random.choice(names_list, replace=False, size=5)

array(['EMİNE ÇETİN', 'Gülsüm', 'Rıza Efe Dönmez ', 'Alihan Ayverdi',
       'Melike Nur ÇOTAK'], dtype='<U22')

In [173]:
np.flipud(liste) # ters cevirme

array([78, 94, 20, ..., 28, 40,  9])

In [174]:
np.max(liste) #maximum

np.int64(100)

In [175]:
np.min(liste) #minumum

np.int64(1)

In [176]:
np.mean(liste) #ortalama

np.float64(50.7187)

In [177]:
np.std(liste) #standart sapma

np.float64(29.04005114165607)

In [178]:
len(liste) #eleman sayısı

10000

In [179]:
notlar = np.random.randint(50, 101, 20)
notlar

array([95, 61, 64, 84, 57, 71, 91, 97, 60, 58, 97, 69, 73, 96, 91, 67, 53,
       93, 72, 87])

In [180]:
np.savetxt("notlar.txt", notlar) #bilimsel gösterim

In [181]:
#bilimsel olmayan gösterim
np.savetxt("notlar.txt", notlar, fmt="%d")

In [182]:
ls

datatypes.jpeg      exercise.ipynb      notlar.txt
ders1.ipynb         kısayollar.jpeg     notlar2.csv
ders2.ipynb         notlar.csv          numpy_array_t.jpeg


In [183]:
notlar = np.loadtxt("notlar.txt")

In [184]:
notlar

array([95., 61., 64., 84., 57., 71., 91., 97., 60., 58., 97., 69., 73.,
       96., 91., 67., 53., 93., 72., 87.])

In [185]:
np.sort(notlar)

array([53., 57., 58., 60., 61., 64., 67., 69., 71., 72., 73., 84., 87.,
       91., 91., 93., 95., 96., 97., 97.])

In [186]:
#reverse sort
np.sort(notlar)[::-1]

array([97., 97., 96., 95., 93., 91., 91., 87., 84., 73., 72., 71., 69.,
       67., 64., 61., 60., 58., 57., 53.])

In [187]:
np.max(notlar), np.min(notlar), np.std(notlar), np.mean(notlar)

(np.float64(97.0),
 np.float64(53.0),
 np.float64(15.12150786132124),
 np.float64(76.8))

In [188]:
sehirler = np.array(["Malatya", "Kahramanmaraş", "Antalya", "Ankara", "Istanbul", "Bursa", "Kütahya", "Malatya"])

In [189]:
np.unique(sehirler)

array(['Ankara', 'Antalya', 'Bursa', 'Istanbul', 'Kahramanmaraş',
       'Kütahya', 'Malatya'], dtype='<U13')

In [190]:
unuqie, counts = np.unique(sehirler, return_counts=True)
sehirler_sozluk = dict(zip(unuqie, counts))
sehirler_sozluk

{np.str_('Ankara'): np.int64(1),
 np.str_('Antalya'): np.int64(1),
 np.str_('Bursa'): np.int64(1),
 np.str_('Istanbul'): np.int64(1),
 np.str_('Kahramanmaraş'): np.int64(1),
 np.str_('Kütahya'): np.int64(1),
 np.str_('Malatya'): np.int64(2)}

In [191]:
sehirler_sozluk["Malatya"]

np.int64(2)

In [192]:
sehir = ""
while True:
    sehir = input("Bir sehir giriniz: ")
    sehir = sehir.capitalize() 

    if sehir not in sehirler_sozluk.keys():
       print("Sehir bulunamadı")
    else:
        print(sehirler_sozluk[sehir]) 
        break

2


In [193]:
frekans = np.asarray((unuqie, counts)).T
print(frekans)

[['Ankara' '1']
 ['Antalya' '1']
 ['Bursa' '1']
 ['Istanbul' '1']
 ['Kahramanmaraş' '1']
 ['Kütahya' '1']
 ['Malatya' '2']]


In [194]:
notlar = np.random.randint(50, 101, 20)
notlar

array([ 57,  77,  83,  89,  98,  63, 100,  75,  97,  84,  56,  82,  52,
        68,  71,  57,  97,  52,  74,  84])

In [195]:
notlar = np.random.randint(50, 101, 20)
notlar.tofile("notlar.csv", sep=",", format="%d")

In [196]:
notlar2 = notlar.reshape(20,1)

In [197]:
notlar2.tofile("notlar2.csv", sep=",", format="%d")

In [198]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [199]:
import pandas as pd

In [200]:
#import with pandas
df = pd.read_csv("notlar.csv")
df

Empty DataFrame
Columns: [70, 65, 84, 72, 80, 73, 98, 79, 59, 86, 62, 88, 53, 86.1, 73.1, 79.1, 83, 93, 56, 61]
Index: []