In [16]:
import numpy as np

In [17]:
np_liste = np.array(list(range(1,11)))
np_2d = np_liste.reshape(5,2)
np_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
np_2d[0]

array([1, 2])

In [19]:
np_5 = np.arange(5,25,5)
np_5

array([ 5, 10, 15, 20])

In [20]:
np1 = np.ones((10,10))
np1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
eyes = np.eye(3,3)
eyes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
liste = np.random.randint(1,101,(10000))
print(liste)

[66 15 12 ... 63 36 91]


In [24]:
np.count_nonzero(liste == 1)

101

In [29]:
names_list = ["Alihan Ayverdi",
"Ahmet KOÇ",
"ÖMER FARUK KÖSE",
"Merve DEMİR",
"Rıza Efe Dönmez ",
"Nergis KAHVECİOĞLU",
"EMİNE ÇETİN",
"Safiye Esmanur AYDAR",
"Yasmın Zhulfayeva",
"Ali Burkay KÜÇÜKAKCA",
"Sıla SARAÇ",
"Melike Nur ÇOTAK",
"Sabahattin MAKİNE",
"Gülsüm",
"Muhammed Mustafa SAVAR"]


np.random.choice(names_list, replace=False, size=5)

array(['Nergis KAHVECİOĞLU', 'Melike Nur ÇOTAK', 'Merve DEMİR',
       'Ali Burkay KÜÇÜKAKCA', 'Alihan Ayverdi'], dtype='<U22')